configured_endpoints: 63
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/straddle%2Fstraddle-9fcdff18526e23737d06a0eedabde4ecceec54df59af2103aaf8f00ca42c08a8.yml
openapi_spec_hash: b88f8f9f4cb5d8dc5e6bbc50a34d3acc
config_hash: 7e72ca450ad980379f33e6613dc9d525
