configured_endpoints: 63
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/straddle%2Fstraddle-80ca3ae235f7fecc2ed651c8d24c9cb3f9ccba2ef5cf2cd84d85533693f2472c.yml
openapi_spec_hash: aeb822d2bf137ffe0679e2d3b4db998f
config_hash: d6d2ce000c1fed01e8287fc47996eb2c
