// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { asTextContentResult } from '@straddleio/straddle-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import type { Metadata } from '../../';
import Straddle from '@straddleio/straddle';

export const metadata: Metadata = {
  resource: 'bridge.link',
  operation: 'write',
  tags: [],
  httpMethod: 'post',
  httpPath: '/v1/bridge/plaid',
  operationId: 'CreatePlaidPaykey',
};

export const tool: Tool = {
  name: 'plaid_bridge_link',
  description:
    'Use Bridge to create a new paykey using a Plaid token as the source. This endpoint allows you to create a secure payment token linked to a bank account authenticated through Plaid.',
  inputSchema: {
    type: 'object',
    properties: {
      customer_id: {
        type: 'string',
        description: 'Unique identifier of the related customer object.',
      },
      plaid_token: {
        type: 'string',
        description: 'Plaid processor token generated by your application for use with the Straddle API.',
      },
      config: {
        type: 'object',
        properties: {
          sandbox_outcome: {
            type: 'string',
            enum: ['standard', 'active', 'rejected'],
          },
        },
        required: [],
      },
      metadata: {
        type: 'object',
        description:
          'Up to 20 additional user-defined key-value pairs. Useful for storing additional information about the paykey in a structured format.',
      },
      'Correlation-Id': {
        type: 'string',
      },
      'Request-Id': {
        type: 'string',
      },
      'Straddle-Account-Id': {
        type: 'string',
      },
    },
  },
};

export const handler = async (client: Straddle, args: Record<string, unknown> | undefined) => {
  const body = args as any;
  return asTextContentResult(await client.bridge.link.plaid(body));
};

export default { metadata, tool, handler };
